spring:
  application:
    name: distributed-url-shortener

  datasource:
    url: jdbc:mysql://localhost:3306/url_shortener
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

app:
  base-url: http://localhost:8080
  rate-limit:
    create-url:
      max-requests: 100
      duration-seconds: 60